---
- name: playbook remove webserver l1e2
  hosts: node1.example.com
  tasks:
  - name: remove httpd package
    yum:
      name: httpd
      state: absent

  - name: delete file index.html
    file:
      path: /var/www/html/index.html
      state: absent

  - name: close tcp port
    firewalld:
      port: 80/tcp
      permanent: true
      state: disabled
...